const actionTypes = {
	PERFORMING_SCROLL: 'PERFORMING_SCROLL',
	STOP_PERFORMING_SCROLL: 'STOP_PERFORMING_SCROLL',
	WINDOW_SCROLLING: 'WINDOW_SCROLLING',
	WINDOW_NOT_SCROLLING: 'WINDOW_NOT_SCROLLING',
	UPDATE_SCROLL_POSITION: 'UPDATE_SCROLL_POSITION',
	UPDATE_BACKGROUND_COLOR: 'UPDATE_BACKGROUND_COLOR'
}

export default actionTypes;